name: data

on:
  push:
    branches:
      - main
    paths:
      - "data/**"

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./data
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Init yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: data-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          data-${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run main process
      run: yarn run main

    - name: Set variable to check if anything changed
      id: is_updated
      run: |-
        echo "##[set-output name=changed;]$(ls -al ./files/*.pmtiles | wc -l)"

    - name: Copy data files
      if: steps.is_updated.outputs.changed != 0
      run: |-
        cp ./files/*.pmtiles ../public/files

    - name: Commit data files
      if: steps.is_updated.outputs.changed != 0
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ../public/files
        git commit -m "Update at $(date +'%Y-%m-%d %H:%M')"

    - name: Push changes
      if: steps.is_updated.outputs.changed != 0
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
